export const MOCK_STORES = [
  {
    id: 1,
    name: 'FreshMart Central',
    email: 'contact@freshmart.com',
    address: '101 Market Street, New York, NY 10001',
    rating: 4.9,
    ownerId: 2,
    ownerName: 'Margaret Elizabeth Johnson',
    ownerEmail: 'margaret.johnson@example.com',
    status: 'active',
    createdAt: '2024-01-20',
    totalReviews: 312,
    category: 'Grocery',
    phone: '+1 (212) 555-0101',
    reviews: [
      { id: 1, user: 'Alice M.',   rating: 5, comment: 'Absolutely love this store. Fresh produce every day!',        date: '2024-11-01' },
      { id: 2, user: 'Bob K.',     rating: 5, comment: 'Best grocery store in the area. Highly recommend.',           date: '2024-10-28' },
      { id: 3, user: 'Carol T.',   rating: 4, comment: 'Great selection, slightly pricey but worth it.',              date: '2024-10-15' },
    ],
  },
  {
    id: 2,
    name: 'Apex Superstore',
    email: 'info@apexsuper.com',
    address: '250 Commerce Ave, Los Angeles, CA 90001',
    rating: 4.7,
    ownerId: 7,
    ownerName: 'Michael Thomas Martinez',
    ownerEmail: 'michael.martinez@example.com',
    status: 'active',
    createdAt: '2024-02-10',
    totalReviews: 278,
    category: 'Supermarket',
    phone: '+1 (310) 555-0202',
    reviews: [
      { id: 1, user: 'David R.',   rating: 5, comment: 'Huge variety and great prices. My go-to store.',             date: '2024-11-03' },
      { id: 2, user: 'Emma S.',    rating: 4, comment: 'Good store overall, parking can be tricky on weekends.',     date: '2024-10-20' },
      { id: 3, user: 'Frank L.',   rating: 5, comment: 'Staff is super helpful and the store is always clean.',      date: '2024-10-10' },
    ],
  },
  {
    id: 3,
    name: 'QuickStop Plus',
    email: 'hello@quickstop.com',
    address: '78 Convenience Blvd, Chicago, IL 60601',
    rating: 4.6,
    ownerId: 11,
    ownerName: 'James Edward Rodriguez',
    ownerEmail: 'james.rodriguez@example.com',
    status: 'active',
    createdAt: '2024-03-05',
    totalReviews: 201,
    category: 'Convenience',
    phone: '+1 (312) 555-0303',
    reviews: [
      { id: 1, user: 'Grace H.',   rating: 5, comment: 'Open 24/7 and always stocked. Perfect for late nights.',     date: '2024-11-02' },
      { id: 2, user: 'Henry P.',   rating: 4, comment: 'Convenient location and friendly staff.',                    date: '2024-10-25' },
      { id: 3, user: 'Iris W.',    rating: 5, comment: 'Clean, well-organized, and fast checkout.',                  date: '2024-10-18' },
    ],
  },
  {
    id: 4,
    name: 'Daily Needs Hub',
    email: 'support@dailyneeds.com',
    address: '33 Essentials Road, Houston, TX 77001',
    rating: 4.4,
    ownerId: 4,
    ownerName: 'Stephanie Marie Thompson',
    ownerEmail: 'stephanie.t@example.com',
    status: 'inactive',
    createdAt: '2024-03-18',
    totalReviews: 189,
    category: 'Grocery',
    phone: '+1 (713) 555-0404',
    reviews: [
      { id: 1, user: 'Jack N.',    rating: 4, comment: 'Good prices but limited organic options.',                   date: '2024-10-30' },
      { id: 2, user: 'Karen B.',   rating: 5, comment: 'Friendly staff and great weekly deals.',                     date: '2024-10-22' },
      { id: 3, user: 'Leo C.',     rating: 4, comment: 'Decent store, could use more checkout lanes.',               date: '2024-10-12' },
    ],
  },
  {
    id: 5,
    name: 'Metro Grocers',
    email: 'metro@grocers.com',
    address: '500 Urban Lane, Phoenix, AZ 85001',
    rating: 4.3,
    ownerId: 14,
    ownerName: 'Barbara Jean Walker',
    ownerEmail: 'barbara.walker@example.com',
    status: 'active',
    createdAt: '2024-04-12',
    totalReviews: 154,
    category: 'Grocery',
    phone: '+1 (602) 555-0505',
    reviews: [
      { id: 1, user: 'Mia D.',     rating: 4, comment: 'Nice store with a good bakery section.',                     date: '2024-11-01' },
      { id: 2, user: 'Noah F.',    rating: 5, comment: 'Love the fresh deli counter. Always fresh!',                 date: '2024-10-27' },
      { id: 3, user: 'Olivia G.',  rating: 4, comment: 'Reasonable prices and good produce.',                        date: '2024-10-14' },
    ],
  },
  {
    id: 6,
    name: 'Sunrise Organics',
    email: 'hello@sunriseorganics.com',
    address: '88 Green Street, San Francisco, CA 94101',
    rating: 4.8,
    ownerId: 17,
    ownerName: 'Charles Robert Hernandez',
    ownerEmail: 'charles.hernandez@example.com',
    status: 'active',
    createdAt: '2024-05-01',
    totalReviews: 267,
    category: 'Organic',
    phone: '+1 (415) 555-0606',
    reviews: [
      { id: 1, user: 'Paul J.',    rating: 5, comment: 'Best organic store in the city. Worth every penny.',         date: '2024-11-04' },
      { id: 2, user: 'Quinn R.',   rating: 5, comment: 'Amazing selection of local produce and eco products.',       date: '2024-10-29' },
      { id: 3, user: 'Rachel S.',  rating: 4, comment: 'A bit expensive but the quality is unmatched.',              date: '2024-10-20' },
    ],
  },
  {
    id: 7,
    name: 'Budget Basket',
    email: 'info@budgetbasket.com',
    address: '12 Savings Drive, Dallas, TX 75201',
    rating: 3.8,
    ownerId: 20,
    ownerName: 'Nancy Carol Lopez',
    ownerEmail: 'nancy.lopez@example.com',
    status: 'inactive',
    createdAt: '2024-06-15',
    totalReviews: 98,
    category: 'Discount',
    phone: '+1 (214) 555-0707',
    reviews: [
      { id: 1, user: 'Sam T.',     rating: 4, comment: 'Great prices, selection is limited but good for basics.',    date: '2024-10-31' },
      { id: 2, user: 'Tina U.',    rating: 3, comment: 'Affordable but the store could be cleaner.',                 date: '2024-10-18' },
      { id: 3, user: 'Uma V.',     rating: 4, comment: 'Best bang for your buck in the neighborhood.',               date: '2024-10-05' },
    ],
  },
  {
    id: 8,
    name: 'Corner Fresh',
    email: 'cornerfresh@mail.com',
    address: '9 Neighborhood Ave, Seattle, WA 98101',
    rating: 4.5,
    ownerId: 2,
    ownerName: 'Margaret Elizabeth Johnson',
    ownerEmail: 'margaret.johnson@example.com',
    status: 'active',
    createdAt: '2024-07-08',
    totalReviews: 143,
    category: 'Convenience',
    phone: '+1 (206) 555-0808',
    reviews: [
      { id: 1, user: 'Victor W.',  rating: 5, comment: 'Tiny but mighty! Everything you need in one spot.',          date: '2024-11-02' },
      { id: 2, user: 'Wendy X.',   rating: 4, comment: 'Love the local vibe and the staff knows your name.',         date: '2024-10-26' },
      { id: 3, user: 'Xander Y.',  rating: 5, comment: 'Fresh sandwiches and great coffee. Daily stop for me.',      date: '2024-10-17' },
    ],
  },
];
