export const MOCK_USERS = [
  { id: 1,  name: 'Jonathan Alexander Smith',   email: 'jonathan.smith@example.com',  address: '123 Maple Street, New York, NY 10001',         role: 'admin',      status: 'active',   createdAt: '2024-01-15' },
  { id: 2,  name: 'Margaret Elizabeth Johnson',  email: 'margaret.johnson@example.com', address: '456 Oak Avenue, Los Angeles, CA 90001',        role: 'storeOwner', status: 'active',   createdAt: '2024-02-03' },
  { id: 3,  name: 'Christopher William Davis',   email: 'chris.davis@example.com',      address: '789 Pine Road, Chicago, IL 60601',             role: 'user',       status: 'active',   createdAt: '2024-02-18' },
  { id: 4,  name: 'Stephanie Marie Thompson',    email: 'stephanie.t@example.com',      address: '321 Birch Lane, Houston, TX 77001',            role: 'storeOwner', status: 'inactive', createdAt: '2024-03-07' },
  { id: 5,  name: 'Robert James Anderson',       email: 'robert.anderson@example.com',  address: '654 Cedar Blvd, Phoenix, AZ 85001',            role: 'user',       status: 'active',   createdAt: '2024-03-22' },
  { id: 6,  name: 'Patricia Anne Wilson',        email: 'patricia.wilson@example.com',  address: '987 Elm Street, Philadelphia, PA 19101',       role: 'user',       status: 'active',   createdAt: '2024-04-10' },
  { id: 7,  name: 'Michael Thomas Martinez',     email: 'michael.martinez@example.com', address: '147 Walnut Drive, San Antonio, TX 78201',      role: 'storeOwner', status: 'active',   createdAt: '2024-04-25' },
  { id: 8,  name: 'Jennifer Lynn Garcia',        email: 'jennifer.garcia@example.com',  address: '258 Spruce Court, San Diego, CA 92101',        role: 'user',       status: 'inactive', createdAt: '2024-05-14' },
  { id: 9,  name: 'David Charles Robinson',      email: 'david.robinson@example.com',   address: '369 Willow Way, Dallas, TX 75201',             role: 'admin',      status: 'active',   createdAt: '2024-05-30' },
  { id: 10, name: 'Susan Katherine Clark',       email: 'susan.clark@example.com',      address: '741 Poplar Place, San Jose, CA 95101',         role: 'user',       status: 'active',   createdAt: '2024-06-08' },
  { id: 11, name: 'James Edward Rodriguez',      email: 'james.rodriguez@example.com',  address: '852 Ash Street, Austin, TX 78701',             role: 'storeOwner', status: 'active',   createdAt: '2024-06-19' },
  { id: 12, name: 'Linda Marie Lewis',           email: 'linda.lewis@example.com',      address: '963 Hickory Road, Jacksonville, FL 32099',     role: 'user',       status: 'inactive', createdAt: '2024-07-02' },
  { id: 13, name: 'William Henry Lee',           email: 'william.lee@example.com',      address: '159 Magnolia Ave, Columbus, OH 43085',         role: 'user',       status: 'active',   createdAt: '2024-07-17' },
  { id: 14, name: 'Barbara Jean Walker',         email: 'barbara.walker@example.com',   address: '357 Chestnut Blvd, Charlotte, NC 28201',       role: 'storeOwner', status: 'active',   createdAt: '2024-08-05' },
  { id: 15, name: 'Richard Allen Hall',          email: 'richard.hall@example.com',     address: '468 Sycamore Lane, Indianapolis, IN 46201',    role: 'user',       status: 'active',   createdAt: '2024-08-21' },
  { id: 16, name: 'Jessica Nicole Young',        email: 'jessica.young@example.com',    address: '579 Dogwood Drive, San Francisco, CA 94101',   role: 'user',       status: 'inactive', createdAt: '2024-09-03' },
  { id: 17, name: 'Charles Robert Hernandez',    email: 'charles.hernandez@example.com','address': '681 Redwood Court, Seattle, WA 98101',       role: 'storeOwner', status: 'active',   createdAt: '2024-09-18' },
  { id: 18, name: 'Dorothy Grace King',          email: 'dorothy.king@example.com',     address: '792 Cypress Street, Denver, CO 80201',         role: 'user',       status: 'active',   createdAt: '2024-10-07' },
  { id: 19, name: 'Thomas Joseph Wright',        email: 'thomas.wright@example.com',    address: '813 Juniper Ave, Nashville, TN 37201',         role: 'user',       status: 'active',   createdAt: '2024-10-22' },
  { id: 20, name: 'Nancy Carol Lopez',           email: 'nancy.lopez@example.com',      address: '924 Laurel Road, Oklahoma City, OK 73101',     role: 'storeOwner', status: 'inactive', createdAt: '2024-11-10' },
];
